on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: 代码质量检测
jobs:
  SonarQube:
    name: SonarQube 检测
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 开始检测
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.projectVersion=${{ github.sha }}
